version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - websocket-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount the Nginx configuration
      - ./nginx/conf.d:/etc/nginx/conf.d

      # Shared volumes for certs and ACME challenges
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot

    restart: always

  websocket-server:
    build: .
    container_name: node-websocket
    # Expose internal port 3000 (not published directly to host)
    expose:
      - "3000"
    restart: always

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    # Certbot also needs the same volumes to share certificates/challenges
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot

    # We'll run certbot commands manually using docker-compose run
    entrypoint: "/bin/sh"

volumes:
  certbot-etc:
  certbot-var:
  certbot-www: