services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - websocket-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
    restart: always

  websocket-server:
    build: .
    container_name: node-websocket
    depends_on:
      - mongo
    expose:
      - "3000"
    environment:
      MONGO_URI: ${MONGO_URI}
    restart: always

  mongo:
    image: mongo:8.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      DBNAME: ${DBNAME}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    restart: always

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot

volumes:
  certbot-etc:
    external: true
  certbot-var:
  certbot-www:
  mongo-data: